# Generated by Django 5.0.3 on 2024-04-04 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_sms"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SMS",
        ),
    ]
