# Generated by Django 2.1.7 on 2019-02-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pages", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="pagemodel",
            name="menu_title",
            field=models.CharField(blank=True, max_length=32),
        )
    ]
