# Generated by Django 2.1.7 on 2019-03-05 08:52

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtaildocs', '0010_document_file_hash'),
        ('pages', '0002_pagemodel_menu_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePageModel',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('images', wagtail.core.fields.StreamField([('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))], blank=True, null=True)),
                ('excerpt', wagtail.core.fields.RichTextField()),
                ('text', wagtail.core.fields.RichTextField()),
                ('source', models.URLField()),
                ('menu_title', models.CharField(blank=True, max_length=32)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
