services:

  semkov-postgres:
    restart: always
    image: postgres:latest
    container_name: semkov-postgres
    environment:
      - POSTGRES_DB=semkov
      - POSTGRES_USER=semkov
      - POSTGRES_PASSWORD=semkov

  semkov-wagtail:
    restart: always
    image: mantiby/semkov:latest
    container_name: semkov-wagtail
    ports:
      - 8898:8898
    links:
      - semkov-postgres
    volumes:
      - /home/manti/www/semkov/:/srv/app/src/
      - /mnt/data/www/semkov/static/:/var/lib/app/static/
      - /mnt/data/www/semkov/media/:/var/lib/app/media/
      - /mnt/data/www/semkov/data/:/var/lib/app/data/
      - /mnt/data/www/semkov/log/:/var/log/app/
    environment:
      - DJANGO_SETTINGS_MODULE=semkov.settings.prod
      - POSTGRES_HOST=semkov-postgres
    command: |
      gunicorn semkov.wsgi:application --bind 0.0.0.0:8898 --workers 2 --log-file /var/log/app/wsgi.log
