# Generated by Django 2.1.7 on 2019-02-15 13:21

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural")
    ]

    operations = [
        migrations.CreateModel(
            name="ForumModel",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                ("text", wagtail.fields.RichTextField()),
            ],
            options={"abstract": False},
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="MessageModel",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "attachments",
                    wagtail.fields.StreamField(
                        [
                            (
                                "attachments",
                                wagtail.blocks.ListBlock(
                                    wagtail.documents.blocks.DocumentChooserBlock()
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                    ),
                ),
                ("text", wagtail.fields.RichTextField()),
            ],
            options={"abstract": False},
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ThreadModel",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "attachments",
                    wagtail.fields.StreamField(
                        [
                            (
                                "attachments",
                                wagtail.blocks.ListBlock(
                                    wagtail.documents.blocks.DocumentChooserBlock()
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                    ),
                ),
                ("text", wagtail.fields.RichTextField()),
            ],
            options={"abstract": False},
            bases=("wagtailcore.page",),
        ),
    ]
