# Generated by Django 2.1.7 on 2019-03-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("forum", "0002_auto_20190215_1407")]

    operations = [
        migrations.AddField(
            model_name="forummodel",
            name="homepage_title",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="forummodel",
            name="is_homepage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="messagemodel",
            name="homepage_title",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="messagemodel",
            name="is_homepage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="threadmodel",
            name="homepage_title",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="threadmodel",
            name="is_homepage",
            field=models.BooleanField(default=False),
        ),
    ]
