# Generated by Django 2.1.7 on 2019-03-06 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("forum", "0003_auto_20190306_1143")]

    operations = [
        migrations.AlterModelOptions(
            name="forummodel",
            options={"verbose_name": "Forum", "verbose_name_plural": "Forums"},
        ),
        migrations.AlterModelOptions(
            name="messagemodel",
            options={"verbose_name": "Message", "verbose_name_plural": "Messages"},
        ),
        migrations.AlterModelOptions(
            name="threadmodel",
            options={"verbose_name": "Thread", "verbose_name_plural": "Threads"},
        ),
    ]
