version: 2
jobs:
  build:
    working_directory: /srv/semkov/src

    docker:
      - image: mantiby/semkov:latest

    steps:
      - checkout

      - run:
          name: Run flake8
          command: flake8
          working_directory: /srv/semkov/src/app

      - run:
          name: Run migrations
          command: python manage.py migrate --settings=core.settings.test
          working_directory: /srv/semkov/src/app

      - run:
          name: Run tests
          command: pytest
          working_directory: /srv/semkov/src/app