# Generated by Django 2.1.7 on 2019-03-06 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("home", "0004_auto_20190306_1143")]

    operations = [
        migrations.AlterModelOptions(
            name="categorymodel",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="homepagemodel",
            options={"verbose_name": "Homepage", "verbose_name_plural": "Homepages"},
        ),
    ]
