# Generated by Django 2.1.7 on 2019-03-06 12:39

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0002_auto_20150616_2121"),
        ("pages", "0003_auto_20190306_1143"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
            options={"abstract": False},
        ),
        migrations.AlterModelOptions(
            name="pagemodel",
            options={"verbose_name": "Page", "verbose_name_plural": "Pages"},
        ),
        migrations.AddField(
            model_name="pagetag",
            name="content_object",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page_tags",
                to="pages.PageModel",
            ),
        ),
        migrations.AddField(
            model_name="pagetag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages_pagetag_items",
                to="taggit.Tag",
            ),
        ),
        migrations.AddField(
            model_name="pagemodel",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="pages.PageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
