# Generated by Django 2.1.7 on 2019-05-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("pages", "0004_auto_20190306_1239")]

    operations = [
        migrations.AddField(
            model_name="pagemodel",
            name="source_title",
            field=models.TextField(blank=True),
        )
    ]
