# Generated by Django 4.2.1 on 2023-05-16 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0007_alter_pagemodel_images_alter_pagetag_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagemodel",
            name="document",
        ),
    ]
