# Generated by Django 2.1.7 on 2019-03-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("ads", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="adsmodel",
            name="homepage_title",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="adsmodel",
            name="is_homepage",
            field=models.BooleanField(default=False),
        ),
    ]
