# Generated by Django 2.1.7 on 2019-03-06 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("ads", "0002_auto_20190306_1143")]

    operations = [
        migrations.AlterModelOptions(
            name="adsmodel",
            options={"verbose_name": "Advert", "verbose_name_plural": "Adverts"},
        )
    ]
