# Generated by Django 4.2.1 on 2023-05-16 10:21

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0003_auto_20190306_1239"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adsmodel",
            name="images",
            field=wagtail.fields.StreamField(
                [
                    (
                        "images",
                        wagtail.blocks.ListBlock(
                            wagtail.images.blocks.ImageChooserBlock()
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
