name: Checks

on:
  push:
    branches:
      - master

jobs:
  checks:

    name: Run Django checks

    runs-on: ubuntu-latest

    services:

      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: semkov
          POSTGRES_PASSWORD: semkov
          POSTGRES_DB: semkov
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Setup UV
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        shell: bash
        run: |
          uv sync --locked --all-extras --dev

      - name: Run pre-commit hooks
        run: |
          uv run pre-commit run --all-files

      - name: Check for missing migrations
        run: |
          uv run manage.py makemigrations --dry-run --check --verbosity=3 --settings=semkov.settings.test

      - name: Run Django system checks
        run: |
          uv run manage.py check --fail-level WARNING --settings=semkov.settings.test

      - name: Run Pytest suite
        run: |
          uv run pytest --create-db --disable-warnings --ds=semkov.settings.test semkov/

      - name: Build docker image
        run: |
          docker build -t mantiby/semkov:latest .
